// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WineAPI.Data;

namespace WineAPI.Migrations
{
    [DbContext(typeof(WineContext))]
    [Migration("20200929165714_added_requierd_dataanotaion")]
    partial class added_requierd_dataanotaion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WineAPI.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostalCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("WineAPI.Models.Manufactuer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("addressId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("addressId");

                    b.ToTable("Manufactuers");
                });

            modelBuilder.Entity("WineAPI.Models.Wine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("amount")
                        .HasColumnType("integer");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("grape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("manufactuerId")
                        .HasColumnType("bigint");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<string>("spaceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("manufactuerId");

                    b.ToTable("Wines");
                });

            modelBuilder.Entity("WineAPI.Models.Manufactuer", b =>
                {
                    b.HasOne("WineAPI.Models.Address", "address")
                        .WithMany("Manufactuers")
                        .HasForeignKey("addressId");
                });

            modelBuilder.Entity("WineAPI.Models.Wine", b =>
                {
                    b.HasOne("WineAPI.Models.Manufactuer", "manufactuer")
                        .WithMany("Wines")
                        .HasForeignKey("manufactuerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
